opt_in_rules:
  - attributes
  - conditional_returns_on_newline
  - closure_spacing
  - force_unwrapping
  - private_outlet
  - switch_case_on_newline
included: # paths to include during linting. `--path` is ignored if present.
  - HabitRPG
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length: 200
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
large_tuple:
  - 3
  - 4
force_unwrapping: error
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
reporter: "emoji"
